spring:
  application:
    name: "umc"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

jwt:
  token:
    secretKey: e4doUSTKEUNtYeSfLfaDMILYD8iHYpi5xtdcBOPzYsA+A2KLzzF8f5I+fKf8Mu0+6zM7MLPcZr5sGtVs+HLX0A==
    expiration:
      access: 14400000   # 4시간

